// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dbContext.VendingMachine.Entities;

public partial class Users
{
    public Guid UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public int Deposit { get; set; }

    public byte Role { get; set; }

    public virtual ICollection<Products> Products { get; } = new List<Products>();
}